### ISSUE TITLE
Program only runs on USB power?

### ISSUE THREAD

**Issue by drftrds87** [michaelwilkinson1992/Shiftlight#1]
I'm trying to use an external power source to power the Arduino nano but the program will not run with an external 12v to VIN. Any help would be appreciated.

**Comment by michaelwilkinson1992** [comment]
You cannot run the Arduino Nano on 12v, it is a 5V Board. You need to build the circuit shown in the schematic, there is a voltage regulator included (LM7805).

You may need to purchase a new board, I would imagine the 12v directly to VIN has done some permanent damage.

**Comment by michaelwilkinson1992** [comment]
Also note: the LM7805 has NO polarity protection, if you accidentally switch the wires during installation, the regulator will be permanently damaged
